# Generated by Django 6.0 on 2025-12-13 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rate",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
