# Generated by Django 6.0 on 2025-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='status',
            field=models.CharField(choices=[('N', 'Not_bought'), ('B', 'Bought'), ('W', 'Waiting')], default='N'),
        ),
    ]
