# Generated by Django 6.0 on 2026-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_bucket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
