# Generated by Django 6.0 on 2026-01-04 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_bucket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
