# Generated by Django 6.0 on 2026-01-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='error',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='status',
        ),
    ]
