# Generated by Django 6.0 on 2026-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_emaillog_error_remove_emaillog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='order_id',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('F', 'Failed')], default='P'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
