# Generated by Django 6.0 on 2026-02-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_bucket_order_id_bucket_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='order_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('F', 'Failed')], default='P'),
        ),
    ]
